defmodule ProjectEulerElixir do
  @moduledoc """
  Documentation for `ProjectEulerElixir`.
  """

  @doc """
  Problem 2
  Even Fibonacci numbers

  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  """

  def main(n) do
    {0, 0}
    |> Stream.iterate(fn
      {0, 0} ->
        {1, 0}

      {a, b} ->
        {a + b, a}
    end)
    |> Stream.map(&Kernel.elem(&1, 1))
    |> Stream.take_while(&(&1 < n))
    |> Enum.reduce(
      &if(rem(&1, 2) == 0) do
        &1 + &2
      else
        &2
      end
    )
  end
end
