defmodule ProjectEulerElixir do
  @moduledoc """
  Documentation for `ProjectEulerElixir`.
  """

  @doc """
  Problem 2
  Even Fibonacci numbers

  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  """

  def main(n) do
    Stream.iterate(0, &(&1 + 1))
    |> Stream.map(&ProjectEulerElixir.fib(&1))
    |> Enum.take_while(&(&1 < n))
    |> Enum.filter(&(rem(&1, 2) == 0))
    |> Enum.sum()
  end

  def fib(0), do: 0
  def fib(1), do: 1
  def fib(n), do: fib(n - 1) + fib(n - 2)
end

IO.inspect(ProjectEulerElixir.main(4_000_000))
